package com.example.demo_springboot.domain;

import java.math.BigDecimal;
import java.util.UUID;

/**
 * ChiTietSp generated by hbm2java
 */
import jakarta.persistence.*;
import lombok.*;

@Data
@Entity
@Table(name = "ChiTietSP", schema = "dbo", catalog = "FINALASS_FPOLYSHOP_FA22_SOF205__SOF2041")
public class ChiTietSp implements java.io.Serializable {

    @Id
    @Column(name = "Id", unique = true, nullable = false, length = 36)
    private UUID id;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "IdDongSP")
    private DongSp dongSp;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "IdMauSac")
    private MauSac mauSac;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "IdNsx")
    private Nsx nsx;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "IdSP")
    private SanPham sanPham;

    @Column(name = "NamBH")
    private Integer namBh;

    @Column(name = "MoTa")
    private String moTa;

    @Column(name = "SoLuongTon")
    private Integer soLuongTon;

    @Column(name = "GiaNhap", precision = 20, scale = 0)
    private BigDecimal giaNhap;

    @Column(name = "GiaBan", precision = 20, scale = 0)
    private BigDecimal giaBan;


}
