package com.example.demo_springboot.domain;



import lombok.Data;

import jakarta.persistence.*;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

/**
 * ChucVu generated by hbm2java
 */
@Data
@Entity
@Table(name="ChucVu"
        ,schema="dbo"
        ,catalog="FINALASS_FPOLYSHOP_FA22_SOF205__SOF2041"
        , uniqueConstraints = @UniqueConstraint(columnNames="Ma")
)
public class ChucVu  implements java.io.Serializable {
    @Id
    @Column(name = "Id", unique = true, nullable = false, length = 36)
    private UUID id;
    @Column(name = "Ma", unique = true, length = 20)
    private String ma;
    @Column(name = "Ten")
    private String ten;
    @OneToMany(fetch=FetchType.LAZY, mappedBy="chucVu")
    private Set<NhanVien> nhanVien= new HashSet<NhanVien>(0);


}