package com.example.demo_springboot.domain;

import java.util.Date;
import java.util.UUID;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import jakarta.persistence.*;


/**
 * NhanVien generated by hbm2java
 */
import lombok.*;

@Entity
@Table(name = "NhanVien",
        uniqueConstraints = @UniqueConstraint(columnNames = "Ma")
)
@Data
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
@RequiredArgsConstructor(onConstructor_={@JsonCreator(mode = JsonCreator.Mode.DELEGATING)})
public class NhanVien implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "Id", unique = true, nullable = false, length = 36)
    @FormField(label = "ID", type = FormField.FieldType.ID)
    private UUID id;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "IdCV")
    @FormField(label = "Chức Vụ", type = FormField.FieldType.SELECT)
    private ChucVu chucVu;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "IdCH")
    @FormField(label = "Cửa Hàng", type = FormField.FieldType.SELECT)
    private CuaHang cuaHang;

    @Column(name = "Ma", unique = true, length = 20)
    @FormField(label = "Mã Nhân Viên", type = FormField.FieldType.TEXT)
    private String ma;

    @Column(name = "Ten")
    @FormField(label = "Tên", type = FormField.FieldType.TEXT)
    private String ten;

    @Column(name = "TenDem")
    @FormField(label = "Tên Đệm", type = FormField.FieldType.TEXT)
    private String tenDem;

    @Column(name = "Ho")
    @FormField(label = "Họ", type = FormField.FieldType.TEXT)
    private String ho;

    @Column(name = "GioiTinh")
    @FormField(label = "Giới Tính", type = FormField.FieldType.TEXT)
    private String gioiTinh;

    @Temporal(TemporalType.DATE)
    @Column(name = "NgaySinh", length = 10)
    @FormField(label = "Ngày Sinh", type = FormField.FieldType.DATE)
    private Date ngaySinh;

    @Column(name = "DiaChi")
    @FormField(label = "Địa Chỉ", type = FormField.FieldType.TEXT)
    private String diaChi;

    @Column(name = "Sdt", length = 30)
    @FormField(label = "Số Điện Thoại", type = FormField.FieldType.TEXT)
    private String sdt;

    @Column(name = "MatKhau")
    @FormField(label = "Mật Khẩu", type = FormField.FieldType.PASSWORD)
    private String matKhau;

    @Column(name = "TrangThai")
    @FormField(label = "Trạng Thái", type = FormField.FieldType.NUMBER)
    private int trangThai;

    @Override
    public String toString() {
        return "NhanVien{" +
                "id=" + id +
                ", chucVu=" + chucVu +
                ", cuaHang=" + cuaHang +
                ", ma='" + ma + '\'' +
                ", ten='" + ten + '\'' +
                ", tenDem='" + tenDem + '\'' +
                ", ho='" + ho + '\'' +
                ", gioiTinh='" + gioiTinh + '\'' +
                ", ngaySinh=" + ngaySinh +
                ", diaChi='" + diaChi + '\'' +
                ", sdt='" + sdt + '\'' +
                ", matKhau='" + matKhau + '\'' +
                ", trangThai=" + trangThai +
                '}';
    }
}
