
package com.example.demo_springboot.domain;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import lombok.*;

import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import jakarta.persistence.*;

/**
 * Nsx generated by hbm2java
 */
@Entity
@Table(name = "NSX",
        schema = "dbo",
        catalog = "FINALASS_FPOLYSHOP_FA22_SOF205__SOF2041",
        uniqueConstraints = @UniqueConstraint(columnNames = "Ma")
)
@Data
@NoArgsConstructor
@AllArgsConstructor
@JsonIgnoreProperties(ignoreUnknown = true)
public class Nsx implements java.io.Serializable {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "Id", unique = true, nullable = false, length = 36)
    @FormField(label = "ID", type = FormField.FieldType.ID)
    private UUID id;

    @Column(name = "Ma", unique = true, length = 20)
    @FormField(label = "Mã Màu Sắc", type = FormField.FieldType.TEXT)
    private String ma;

    @Column(name = "Ten")
    @FormField(label = "Tên Màu Sắc", type = FormField.FieldType.TEXT)
    private String ten;

    public Nsx(String id) {
        this.id = UUID.fromString(id);
    }

    @Override
    public String toString() {
        return ten;
    }
}